name: Supabase Keep-Alive Ping

on:
  schedule:
    # Runs the workflow every day at 8:00 AM UTC.
    - cron: '0 8 * * *'
  
  # Enables manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase to keep project alive
        run: |
          curl -i -X POST "https://njhroscmwtskxtasotkf.supabase.co/rest/v1/rpc/is_online" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'
